### ISSUE TITLE
Lua

### ISSUE THREAD

**Issue by mytchel** [DandyHQ/mace#21]
Do we want to keep Lua? If we remove Lua do we want to have some other way to extend Mace? We could go back one of the original ideas Vaughan had with multiple processes talking over pipes. Or we could just have a few commands defined in C and add anything as needed. It would simplify Mace but could make it less worth using.

Thoughts and opinions?

**Comment by vkitchen** [comment]
I'm glad you raised this.

How have you found the difficulty in integrating Lua? The little I played with it, it didn't seem bad.
That being said. I think Mace would be a perfectly usable text editor without it being extensible. At the moment with Atom, the only packages I have installed are to add syntax highlighting support for a number of non-default languages. Otherwise the defaults aren't too bad.

If removing Lua will indeed make development easier. Then I agree with doing it

**Comment by mytchel** [comment]
It hasn't been too hard, that being said lua.c is twice the size of any of the other files and doesn't add very much functionality other than the initialization file. 

Yes it is cool being able to program your text editor but not particularly useful. Being able to have some commands would be sufficient. Maybe in the future being able to write your own and have some way to load them as modules would be useful. 

I think vi's ability to compose functions is very useful but we have no way of doing that. Emacs has proven itself to be very versatile and extensible but is that really useful? Yes you can use it for email, IRC, web browsing and a large number of things it never gets used for. Any text editor could do most of these things by operating on a file then letting another program do the rest. 

The only use case I can see is to facilitate integrating Mace with development environments we have not thought of and syntax highlighting. 

I think for now we should remove Lua and use something else for the initialization file. Whatever that may be.

**Comment by mytchel** [comment]
I have removed Lua. Who wants to create an init file or integrate a library for an init file?

**Comment by vkitchen** [comment]
I wouldn't mind doing it. But I haven't finished exams yet. Perhaps a simple ini format would suffice? https://github.com/benhoyt/inih

**Comment by mytchel** [comment]
Looks good.
