### ISSUE TITLE
Crash on closing and reopening file

### ISSUE THREAD

**Issue by vkitchen** [DandyHQ/mace#47]
Steps to reproduce:
1. Open any file
2. Place cursor in file
3. Close the file
4. Open a new file by right clicking on its name.
Affects ce437f41108cfa1c8143d872f6e18798aac7d1b9 and probably later versions.

**Comment by mytchel** [comment]
It's because openfile in cmd.c uses mace->cursels without checking them. When you follow your steps there are no cursels so the cursel s is NULL and you are attempting to dereference it. You should probably use mace->mousefocus to get the text box that was clicked on then get the pane from there.

Or, you could change how textboxbuttonpress works so that it doesn't remove the command cursel until after the command has be called. This is probably sensible but you should check mace->cursels is not null before using it anyway.
