### ISSUE TITLE
Auto indent can double indent

### ISSUE THREAD

**Issue by vkitchen** [DandyHQ/mace#53]
Steps to reproduce.
1. Place cursor at beginning of a line with indent
2. Press enter

What should occur:
A blank line should be inserted where the cursor is shifting the selected line down. The selected line should keep its indent
What does happen:
The selected line gets the indent it currently has added to it, causing it to be double indented.

**Comment by mytchel** [comment]
Any progress?

**Comment by rycoll** [comment]
Ah, I totally forgot about this... I'll have a look at it tomorrow!

**Comment by rycoll** [comment]
I can't seem to reproduce this anymore - can anyone else? Has it somehow been fixed?

**Comment by mytchel** [comment]
It hasn't. Open a new tab, put some spaces then some text say:
'          hello'.
Put the cursor halfway through the spaces and press return.
It will shift the indentation across because it thinks all 10 spaces are the indentation when it would be more natural for it to only be the five before the cursor.
